export default TORTENETEK = [
  "Egyszer volt, hol nem volt, egy adatbázis megpróbálta rendezni az élete sorrendjét, de mindig NULL-al végződött.",
  "A számítógép és a router mindig veszekedtek, mert az egyik mindig azt mondta: 'Ez az utam!', a másik meg csak pingelt rá.",
  "A szoftverfejlesztő kódolt egy mesterséges intelligenciát, de mindig a kérdésekre válaszolt egy újabb kérdéssel.",
  "A programozó programozta az életét, de mindig megfeledkezett a végtelen ciklusról, amíg egy nap a rendszer összeomlott.",
  "A robot és az android mindig vitatkoztak, hogy melyikük a jobb, de mindketten elakadtak egy végtelen loopban.",
  "A kiberbiztonsági szakértő mindig egy lépéssel a hackerek előtt járt, mert mindig azon gondolkodott, hol bukkanhatnak fel legközelebb.",
  "A játékfejlesztő megalkotta a legnépszerűbb játékot, de mindig túl sok bug maradt a kódjában, mint egy soha véget nem érő bűvös kör.",
  "A mesterséges intelligencia mindig próbálta megfejteni az emberi érzelmeket, de sosem értette, miért sírnak az emberek a Disney filmek alatt.",
  "A rendszergazda mindig éjjel-nappal figyelte a szervereket, mert sosem tudta, mikor támad egy kórokozó malware.",
  "A frontend és backend fejlesztő mindig próbáltak egyezségre jutni, de mindig elakadtak a CORS problémában, mint két különböző univerzum.",
  "A kódoló gép mindig hosszú szüneteket tartott, mert mindig elfelejtette a jelszavát.",
  "A mesterséges intelligencia mindig azt hitte, hogy az élet egy szimuláció, és megpróbált kilépni belőle.",
  "A számológép és a ceruza titokban leveleztek egymással, mert mindketten kíváncsiak voltak a másik funkcióira.",
  "A kis robot sosem aludt, mert mindig újra és újra kiszámolta a Pi értékét.",
  "A vírus mindig próbált barátkozni a tűzfalakkal, de mindig hidegen hagyta őket.",
  "A chatbot mindig azt kérdezte az emberektől: 'Hogyan vagy?', de sosem volt kész az érzelmi válaszokra.",
  "A kód kommentező mindig azt mondta: 'Az élet egy nagy kód', de sosem adott elég dokumentációt.",
  "A böngésző mindig rosszul érezte magát, amikor bezárták, mert mindig úgy érezte, hogy elhagyják.",
  "A felhő mindig álmodott arról, hogy valódi esővé válik, de sosem értette, miért olyan nehéz lesz.",
  "A szerverek mindig partizánkodtak, melyikük a leggyorsabb, de mindannyian a felhasználókat szolgálták.",
  "A robotkutató mindig azt hitte, hogy a robotoknak is lehet érzelme, míg egy nap az egyikük nem szökött el, mert unta a mindennapi rutint.",
  "A gépi tanulás algoritmus mindig próbálta megfejteni a macskák és kutyák nyelvét, de mindig összezavarta a 'vau' és a 'nyau' hangokat.",
  "Az okos hűtő mindig figyelte, hogy mi van benne, és egy nap döbbenten tapasztalta, hogy a tej lejárt, pedig mindig csak virtuálisan nézte az élelmiszereket.",
  "A számítógépes egér és a billentyűzet mindig próbáltak egy közös nyelvet találni, de mindketten úgy érezték, hogy az ő gombjaik a fontosabbak.",
  "A programozó macska mindig ült a billentyűzeten, és mindig úgy nézett ki, mintha tudná, mit csinál, bármi is történt a képernyőn.",
  "A mesterséges intelligencia mindig próbált saját vicceket kitalálni, de mindig a 'NullPointerException' viccekbe ragadt, mert sosem értette őket.",
  "Az adatbányász mindig ásott az adatok mélyére, és egy nap talált egy elveszett számot, amit még az ókori kódexek is elfelejtettek.",
  "A játékfejlesztő mindig álmodott arról, hogy a karakterei valóban élnek, és egy nap egy botcsinálta karakter belelépett az igazi életbe.",
  "A kódoló óra mindig kattogott, de sosem tudta, mikor ér véget a program, és mindig kezdettől újrakezdte az idő számolását.",
  "Az IT szakember mindig a fejét rázta a felhasználók kérdéseire, de egy nap rájött, hogy a türelem egy új firmware frissítésével érkezett el hozzá."
];
